### ISSUE TITLE
Tracking Issue: Package `portalnetwork` for distribution

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ultralight#192]
One glaring deficiency in our current monorepo is we do zero packaging for `portalnetwork` which is the centerpiece of the library as intended to be a toolkit for dapps and wallets to integrate Portal Network functionality into their code. There are a number of steps needed to really make this work:
- [ ] ~~Figure out the best way to package up `portalnetwork` as both an ESM module and CommonJS.  Currently, we just output CommonJS code from the Typescript compiler.  A likely way forward would be to add Rollup back in and have it do this for us~~.
- [x] ~~Remove `discv5` package from monorepo by passing needed changes back upstream to @chainsafe/discv5.~~  #233 necessitated reopening this one.  Will close if/when we're able to merge an upstream PR on the discv5 repo. We're able to close again thanks to #256 
- [x] ~~Re-export any `discv5`` specific interfaces from `portalnetwork` so `discv5` is no longer a peer dependency required for installation (e.g. re-export `ITransportInterface` so other networking layers can be implemented like react native)~~ (covered by #210 
- [x] Publish `portalnetwork` on NPM - This is technically done already but nobody should be using the version that's currently out there as it's unusable without our discv5 fork.
- [x] Implement a fully usable `JsonRpcProvider` that uses `portalnetwork` where feasible or a fallback provider otherwise. #359 #364

There's probably more to this but this would be a starting point.

**Comment by acolytec3** [comment]
Going to close this for now.
