### ISSUE TITLE
Upgrade main dependencies to latest versions

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ultralight#221]
We should work to upgrade several key dependencies in our stack:
- [ ] `discv5` to 1.0 at least - halfway done though we're still on a fork #303 
- [x] `rlp` to 4.0 - #321 
- [x] `ssz` to 0.9 done in #224 
- [ ] `EthereumJS` to latest releases - in flight with #359 

This will allow us to use `Uint8arrays` instead of `buffers` internally (except for the `@EthereumJS/block` which still isn't using RLP 3 internally so we may get buffers back from it)

**Comment by acolytec3** [comment]
I have a branch in progress upgrading SSZ.

**Comment by acolytec3** [comment]
This done.
