### ISSUE TITLE
Tracking Issue: Implement Header Gossip subprotocol

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ultralight#223]
Build out header gossip subprotocol
- [x] Define SSZ data types for `headerAccumulator` and `epochAccumulator` #213 
- [x] Define utility method to update accumulator with new header #213 
- [x] Create a new `headerAccumulator` class #231 
- [x] Define methods to generate and validate proofs of historical header inclusion in a given `epochAccumulator`, partially completed in  #231 
- [ ] Define serialization/deserialization of header proofs
- [ ] Build message handlers to share accumulator snapshots, header proofs, and latest headers
- [x] Logic to validate newly received header is next in line to add to accumulator

There's probably more here

**Comment by acolytec3** [comment]
In #220, I've added a test that demonstrates how to generate a multiproof that can be used to verify every header record in a given `epochAccumulator` but this would be unwieldy for purposes of validating inclusion of a single header within a given epoch.  Further research needed on this front.

**Comment by acolytec3** [comment]
#231 brings in our header accumulator class.  Next is to add it to the main client and begin building out the message handling.

**Comment by acolytec3** [comment]
In #262 I reworked the tests to use the `headerAccumulatorType` instead of the `epochAccumulator` and also added a new test to validate a proof of a header in the current epoch but using the `headerAccumulatorType.createProof` instead of the `epochAccumulator`.

**Comment by acolytec3** [comment]
Going to close this as the accumulator stuff is now under the history network and a lot of the work is done.
