### ISSUE TITLE
Beacon Subprotocol buildout

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ultralight#452]
Tracking Issue for Beacon Subprotocol work
- [x] Beacon network light client data types
- [x] Protocol scaffolding
- [x] FindContent flow handling
- [x] LightClientUpdatesByRange handling
- [ ] Offer/Accept content gossip
  - [x] Think through gossip logic (currently just offers all content to 5 random nodes)
  - [x] Ensure types match work on [this pr](https://github.com/ethereum/portal-network-specs/pull/217)
  - [ ] Add intelligent handling for `LightClientUpdatesByRange`
- [ ] Lodestar light client integration
  - [x] Happy path syncing from only portal network data
  - [x] Light client sync from Beacon chain - works now using the `beaconBridge` script
  - [x] Add logic within `portalnetwork` for bootstrapping light client from sample of lightclient updates retrieved from multiple peers - #460 
  - [x] Update `optimisticUpdate`/`finalityUpdate` to use `signatureSlot` as reference slot for requests
- [ ] Figure out `historicalSummaries`  ~~and `historicalRoots`~~ object and how to store/gossip 
- [ ] Make typing easier to read and work with
  - [x] Clean up all the `(ssz as any)...` - solved by #475 475
  - [ ] Make better handlers for getting content keys creating data
  - [ ] Simplify forkdigest logic
- [x] Integrate into CLI and allow initializing light client just from Portal Network data
  - [x] #456 - initial PoC integrating `cli`
- [ ] Integrate into browser client

**Comment by acolytec3** [comment]
Will close for now.  There's more to do here but we don't need this and it's out of date anyway.
