### ISSUE TITLE
Support `eth_call` from Ultralight

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ultralight#491]
- [x] Finish #488 to pipe in State Network data
- [x] Ensure that `findRecursiveContent` works for `state` network #514 
- [x] Implement `UltralightStateManager` that implements `@ethereumjs/statemanager` interface #515 
- [x] Add tests for `evm.runCall` using `UltralightStateManager` #514, #505
- [x] Add `eth_call` #515 #524 
- [x] Add caching and support `put` operations in `UltralightStateManager` #525 
- [ ] Create devnet test script that leverages `stateBridge` to pipe in data and then run `eth_call` against recent blocks between nodes

**Comment by acolytec3** [comment]
Gonna call this done for now.  With state network specs changing, no point in building too much on this until we get a more final spec.
