### ISSUE TITLE
Support header verification and construction for post-merge proofs

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ultralight#597]
In the History network, post-merge headers require a proof that is rooted in the `historicalRoots` or `historicalSummaries` accumulator from the Beacon chain state.  These are constructed from a set of merkle proofs showing inclusion of an EL header in a beacon block body, the beacon block header, and then up to the `historicalRoots`/`historicalSummaries` accumulator as documented in [these](https://github.com/ethereum/portal-network-specs/pull/287) [two](https://github.com/ethereum/portal-network-specs/pull/291) PRs.  To allow Ultralight to properly verify these headers we need to build out the following bits:
- [x] ~~`history.verifyInclusionProof` needs to be modified to verify post-merge header proofs against the correct accumulator `` Replaced `verifyInclusionProof` with multiple proof verification utilities
- [x] We need to build some helper methods/bridge scripts to construct these header proofs leveraging a beacon block body requested from a beacon node. #600 + #616 accomplish this
- [x] Build out types for `historicalSummariesBlockHeaderProof` in the history network #616
- [x] Support the `historicalSummaries` data object in gossip and findContent methods in the beacon network #606
- [ ] Link up HistoricalSummaries stored in Beacon Network to proof verification of post capella blocks in history network

**Comment by acolytec3** [comment]
This is feasible to finish now that we can get historical summaries from lodestar
