### ISSUE TITLE
Checklist for things to do to support local testnet

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ultralight#86]
We need a way to spin up a bunch of CLI nodes locally to allow us to do more rigorous testing of our implementation of the portal network spec.
~~- [x] Functional docker image that exposes ports within docker daemon to allow intra-node communcation.  #95 introduces a minimally viable version of this though the cli client docker image needs some improvement to slim down the image size~~
~~- [x] A script to spin up multiple docker instances that ensures that the RPCs for each node are on different ports so we can interact with all of them. #95 introduces a minimally viable version of this that launches the proxy and two cli clients that can find each other~~
- [x] A bash script to spin up multiple CLI clients
- [x] A script to seed the network with some block data
- [x] Update RPC method `eth_getBlockByHash` to use the new `contentLookup` method for retrieving content
- [x] Add RPC method for FINDNODES
- [x] Add RPC method for OFFER
- [x] Add prometheus data monitoring/grafana dashboards to monitor health of the network (a start at this has been made with #120, #122, #123 but more work is needed)

**Comment by emersonmacro** [comment]
@acolytec3 I have a decent amount of experience with Docker and docker-compose. Definitely willing to help with the functional docker image and a docker-compose script if that's of interest

**Comment by acolytec3** [comment]
That'd be great if you have time. The branch I linked to sort of works in so far as the image will build and the node starts up. But the container was something like 1.5GB so seems like it's way too big.  Also,, each container would need to expose the entire udp port range (at least to the docker daemon) and then publish an RPC port accessible outside the container so we could interact with each client.

**Comment by acolytec3** [comment]
With #100, we're down to a 745MB docker image.  It's still tricky to build and will only run on intel processors (though we can probably figure out how to have it compile `bcrypto` for ARM if someone wants to run this on a raspberry pi (probably just easier to build from source).

**Comment by acolytec3** [comment]
#101 adds a content loading method to the RPC for the CLI.

**Comment by acolytec3** [comment]
#102 adds a generalized `contentLookup` method that can be wired into `eth_getBlockByHash` for content retrieval

**Comment by acolytec3** [comment]
#116 adds the necessary scripts to start up an ephemeral network of `cli` nodes and then seed one of them with data
An initial run shows that our nodes are not very good at finding each other or sharing content :grimacing:

**Comment by holgerd77** [comment]
I think it would be beneficial I you guys switch over to adhere to deeper reaching x-reviews on each PR since all bugs introduced in a peer-to-peer/networking layer can be very costly and extremely hard to debug and find afterwards some times.

We've seen this a lot of times in the `devp2p` context. In some cases it took years (!!) until we were finally able to locate rather central bugs which substantially diminished the connectivity. 😬

**Comment by acolytec3** [comment]
> I think it would be beneficial I you guys switch over to adhere to deeper reaching x-reviews on each PR since all bugs introduced in a peer-to-peer/networking layer can be very costly and extremely hard to debug and find afterwards some times.
> 
Would definitely love to see more of this, especially in terms of the "business logic" of content and node lookups.  I suspect the initial implementations I've done are far too naive and fragile but we need more testing and experimentation with this code to find out.  Spinning up these ephemeral devnets has been a useful starting point as it already demonstrates that nodes don't find each other very easily with our current setup.  I'll continue down this path (especially with more discrete metrics reporting which has already proven useful in its nascent form to demonstrate the lack of connectivity between nodes).

**Comment by acolytec3** [comment]
This is basically resolved with the merge of #130.  Will open a new dedicated issue for metrics.
